import Head from "next/head";
import Image from "next/image";
import React from "react";
import Link from "next/link";
import Menu from "./comps/Menu";
import router from "next/router";
import ShoppingCartIcon from "@material-ui/icons/ShoppingCart";
import { useSelector } from "react-redux";

export default function Header() {
  const cart = useSelector((state) => state.cart);

  const { cartItems } = cart;

  const getCartCount = () => {
    return cartItems.reduce((qty, item) => qty + item.qty, 0);
  };
  return (
    <div>
      <Head>
        {/* <tittle>BedsDivans</tittle> */}
        <meta name="description" content="Generated by create next app" />
        <link
          rel="stylesheet"
          href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"
        ></link>
        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css"
        ></link>
        <link href="/style/plugins/plugins.min.css/" rel="stylesheet"></link>
        <link href="/style/vendor/vendor.min.css/" rel="stylesheet"></link>
        <link rel="icon" href="/logo (1).png" />
      </Head>

      <div className="header section">
        <div className="classic-header">
          <div className="header-top section-fluid   ">
            <div className="container">
              <div className="row row-cols-lg-2 align-items-center">
                <div className="col text-center text-lg-left">
                  <div className="header-top-massege">
                    <p>Free Delivery over £40 to most of UK*</p>
                  </div>
                </div>

                <div className="col d-none d-lg-block">
                  <div className="header-top-set-lan-curr d-flex justify-content-end">
                    <div className="header-top-content">
                      <a href="/contact">
                        <button> Contact Us </button>
                      </a>
                    </div>

                    <div className="header-top-content">
                      <a href="/about">
                        <button>About us</button>
                      </a>
                    </div>
                    <div className="header-top-content">
                      <button>01902405535</button>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
        <div className="header-bottom d-none d-lg-block">
          <div className="container position-relative Ncs ">
            <div className="row align-self-center">
              <div className="col-md-2 align-self-center">
                <div className="header-logo">
                  <a href="">
                    <Image
                      alt="BedsDivan"
                      src="/assets/images/logo/logo.png"
                      width={118}
                      height={118}
                    />
                  </a>
                </div>
              </div>
              <div className="col-md-6 align-self-center">
                <div className="header-actions search-section">
                  <div className="header_search-form">
                    <form className="action-form" action="#">
                      <input
                        className="form-control"
                        placeholder="Search for Products----------------"
                        type="text"
                      />
                      <button className="submit" type="submit">
                        <i className="icon-magnifier"></i>
                      </button>
                    </form>
                  </div>
                  {/* <span
                    href="#"
                    className="header-action-btn header-action-btn-cart"
                    title="Wishlist"
                  >
                    <i className="icon-heart"></i>
                    <span className="header-action-num">05</span>
                  </span> */}
                  <span
                    onClick={() => router.push("/cart")}
                    className="header-action-btn header-action-btn-cart offcanvas-toggle pr-0"
                    style={{ cursor: "pointer" }}
                  >
                    <ShoppingCartIcon />
                    <span className="header-action-num">{getCartCount()}</span>
                  </span>
                </div>
              </div>

              <div className="col-md-4 align-self-center">
                <div className="header-actions">
                  <div className="header-bottom-set dropdown">
                    <ul>
                      <button className="login-button">
                        <a href="#" style={{ color: "#262884" }}>
                          <b>Login</b>
                        </a>
                      </button>

                      <button className="ReadMorB">
                        <span style={{ color: "#7c7c7c" }}>or</span>
                        <a href="#" style={{ color: "#292929" }}>
                          <b>Register</b>
                        </a>
                      </button>
                      <button className="box-imgN">
                        <Image
                          alt="BedsDivan"
                          src="/assets/images/banner/Group358.png"
                          width={58}
                          height={50}
                        />
                      </button>
                    </ul>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
        <div className="header-bottom d-lg-none sticky-nav bg-white">
          <div className="container position-relative">
            <div className="row align-self-center">
              <div className="col-auto align-self-center">
                <div className="header-logo">
                  <a href="#">
                    <Image
                      src="/assets/images/logo/logo.png"
                      width={128}
                      height={128}
                      alt="Site Logo"
                    />
                  </a>
                </div>
              </div>

              <div className="col align-self-center">
                <div className="header-actions">
                  <div className="header_account_list">
                    <a className="header-action-btn search-btn">
                      <i className="icon-magnifier"></i>
                    </a>
                    <div className="dropdown_search">
                      <form className="action-form" action="#">
                        <input
                          className="form-control"
                          placeholder="Enter your search key"
                          type="text"
                        />
                        <button className="submit" type="submit">
                          <i className="icon-magnifier"></i>
                        </button>
                      </form>
                    </div>
                  </div>

                  <div className="header-bottom-set dropdown">
                    <button
                      className="dropdown-toggle header-action-btn"
                      data-bs-toggle="dropdown"
                    >
                      <i className="icon-user"></i>
                    </button>
                    <ul>
                      <li>
                        <a className="dropdown-item" href="my-account.html">
                          My account
                        </a>
                      </li>
                      <li>
                        <a className="dropdown-item" href="checkout.html">
                          Checkout
                        </a>
                      </li>
                      <li>
                        <a className="dropdown-item" href="login.html">
                          Sign in
                        </a>
                      </li>
                    </ul>
                  </div>

                  <a
                    href="#offcanvas-cart"
                    className="header-action-btn header-action-btn-cart offcanvas-toggle pr-0"
                  >
                    <i className="icon-handbag"></i>
                    <span className="header-action-num">01</span>
                  </a>
                  <a
                    href="#offcanvas-mobile-menu"
                    className="header-action-btn header-action-btn-menu offcanvas-toggle d-lg-none"
                  >
                    <i className="icon-menu"></i>
                  </a>
                </div>
              </div>
            </div>
          </div>
        </div>

        {/* For Mobile Menu Components start */}

        <div className="MenuforMobile">
          <Menu />
        </div>
        {/* For Mobile Menu Components start */}
        <div
          className="d-none d-lg-block sticky-nav"
          style={{ backgroundColor: "#204697" }}
        >
          <div
            className="container position-relative"
            style={{ maxWidth: "100%" }}
          >
            <div className="row">
              <div className="col-md-12 align-self-center">
                <div className="main-menu manu-color-white">
                  <ul>
                    {/* <li className="dropdown position-static"><a href="/DivanBed"> <b>Divan Beds</b> </a> */}
                    <li className="dropdown position-static ">
                      <Link className="ForBold" href="/product/divanbed">
                        Divan Beds
                      </Link>
                      <ul className="mega-menu d-block">
                        <li className="d-flex">
                          <ul className="d-block">
                            <li>
                              <a className="p-0 " href="shop-left-sidebar.html">
                                <Image
                                  className="img-responsive w-100 "
                                  src="/assets/images/banner/beds-nav.jpg"
                                  width={258}
                                  height={238}
                                  alt="BedsDivan"
                                />
                              </a>
                            </li>
                          </ul>

                          <ul className="d-block">
                            <li className="title">
                              <a href="#" style={{ color: "#262884" }}>
                                <b> Shop by Type </b>
                              </a>
                            </li>
                            <li>
                              <Link href="/divanbed/linen-Fabric-Divan-Beds">
                                Linen Fabric Divan Beds
                              </Link>
                            </li>
                            <li>
                              <Link href="/divanbed/velvet-Fabric-Divan-Beds">
                                Velvet Fabric Divan Beds
                              </Link>
                            </li>
                            <li>
                              <a href="shop-left-sidebar.html">
                                Suede Fabric Divan Bed
                              </a>
                            </li>
                            <li>
                              <a href="shop-right-sidebar.html">
                                Low Divan Beds
                              </a>
                            </li>
                            <li>
                              <a href="shop-right-sidebar.html">
                                Leather Divan Beds
                              </a>
                            </li>
                            <li>
                              <a
                                href="shop-right-sidebar.html"
                                style={{ color: "#262884" }}
                              >
                                <b>View All</b>
                              </a>
                            </li>
                          </ul>
                          <ul className="d-block">
                            <li className="title">
                              <a href="#" style={{ color: "#262884" }}>
                                <b> Shop by size </b>
                              </a>
                            </li>
                            <li>
                              <a href="single-product.html">
                                Small Single (2?6)
                              </a>
                            </li>
                            <li>
                              <a href="single-product-variable.html">
                                Single (3?0)
                              </a>
                            </li>
                            <li>
                              <a href="single-product-affiliate.html">
                                Small Double (4?0)
                              </a>
                            </li>
                            <li>
                              <a href="single-product-group.html">
                                Double (4?6)
                              </a>
                            </li>
                            <li>
                              <a href="single-product-tabstyle-2.html">
                                King (5?0)
                              </a>
                            </li>
                            <li>
                              <a href="single-product-tabstyle-3.html">
                                Super King (6?0)
                              </a>
                            </li>
                          </ul>
                          <ul
                            className="d-block"
                            style={{ marginRight: "0px !important" }}
                          >
                            <li className="title">
                              <a href="#" style={{ color: "#262884" }}>
                                <b> Divan Beds Complete Set</b>
                              </a>
                            </li>
                            <li>
                              <a href="shop-3-column.html">
                                Linen Fabric Divan Beds
                              </a>
                            </li>
                          </ul>
                        </li>
                        <li></li>
                      </ul>
                    </li>
                    <li className="dropdown position-static">
                      <Link className="ForBold" href="/product/allbeds">
                        All Beds
                      </Link>

                      <ul className="mega-menu d-block">
                        <li className="d-flex">
                          <ul className="d-block">
                            <li>
                              <a className="p-0" href="shop-left-sidebar.html">
                                <Image
                                  className="img-responsive w-100"
                                  src="/assets/images/banner/Mattresses-nav.jpg"
                                  width={258}
                                  height={238}
                                  alt="BedsDivan"
                                />
                              </a>
                            </li>
                          </ul>
                          <ul className="d-block">
                            <li className="title">
                              <a href="#" style={{ color: "#262884" }}>
                                <b> Sleigh Beds </b>
                              </a>
                            </li>
                            <li>
                              <a href="shop-3-column.html">Florida Bed Range</a>
                            </li>
                            <li>
                              <a href="shop-4-column.html">Ambassador Range</a>
                            </li>
                            <li>
                              <a href="shop-right-sidebar.html">Kendall Bed</a>
                            </li>
                            <li>
                              <a href="shop-right-sidebar.html">Manoco Range</a>
                            </li>
                            <li>
                              <a href="shop-right-sidebar.html">Royal Beds</a>
                            </li>
                            <li>
                              <a href="shop-right-sidebar.html">
                                Swan Bed Range
                              </a>
                            </li>
                            <li>
                              <a href="shop-right-sidebar.html">
                                Wing Bed Range
                              </a>
                            </li>
                            <li>
                              <a href="shop-right-sidebar.html">
                                Winchester Bed
                              </a>
                            </li>
                          </ul>
                          <ul className="d-block">
                            <li className="title1">
                              <a href="#" style={{ color: "#262884" }}>
                                <b>Ottoman Beds</b>
                              </a>
                            </li>
                            <li className="title1">
                              <a href="#" style={{ color: "#262884" }}>
                                <b>Kids Beds</b>
                              </a>
                            </li>
                            <li className="title1">
                              <a href="#" style={{ color: "#262884" }}>
                                <b>Leather beds</b>
                              </a>
                            </li>
                            <li className="title1">
                              <a href="#" style={{ color: "#262884" }}>
                                <b>Nevada Beds</b>
                              </a>
                            </li>
                            <li className="title1">
                              <a href="#" style={{ color: "#262884" }}>
                                <b>Storage Bed</b>
                              </a>
                            </li>
                          </ul>
                          <ul
                            className="d-block"
                            style={{ marginRight: "0px !important" }}
                          >
                            <li className="title">
                              <a href="#" style={{ color: "#262884" }}>
                                <b> Divan Beds </b>
                              </a>
                            </li>
                            <li>
                              <a href="shop-3-column.html">
                                Linen Fabric Divan Beds
                              </a>
                            </li>
                            <li>
                              <a href="shop-4-column.html">
                                Velvet Fabric Divan Beds
                              </a>
                            </li>
                            <li>
                              <a href="shop-left-sidebar.html">
                                Suede Fabric Divan Bed
                              </a>
                            </li>
                            <li>
                              <a href="shop-right-sidebar.html">
                                Low Divan Beds
                              </a>
                            </li>
                            <li>
                              <a href="shop-right-sidebar.html">
                                Leather Divan Beds
                              </a>
                            </li>
                            <li>
                              <a
                                href="shop-right-sidebar.html"
                                style={{ color: "#262884" }}
                              >
                                <b>View All</b>
                              </a>
                            </li>
                          </ul>
                        </li>
                      </ul>
                    </li>
                    <li className="dropdown position-static">
                      <Link href="/product/headboard"> Headboard </Link>

                      <ul className="mega-menu d-block">
                        <li className="d-flex">
                          <ul className="d-block">
                            <li>
                              <a className="p-0" href="shop-left-sidebar.html">
                                <Image
                                  className="img-responsive w-100"
                                  src="/assets/images/banner/headboard-nav.jpg"
                                  width={258}
                                  height={238}
                                  alt="BedsDivan"
                                />
                              </a>
                            </li>
                          </ul>
                          <ul className="d-block">
                            <li className="title">
                              <a href="#" style={{ color: "#262884" }}>
                                <b>Shop by Type</b>
                              </a>
                            </li>
                            <li>
                              <a href="#">Panerl Headboard</a>
                            </li>
                            <li>
                              <a href="#">Cube Headboard</a>
                            </li>
                            <li>
                              <a href="#">Plain Headboard</a>
                            </li>
                            <li>
                              <a href="#" style={{ color: "#262884" }}>
                                <b>View All</b>
                              </a>
                            </li>
                          </ul>

                          <ul className="d-block">
                            <li className="title">
                              <a href="#" style={{ color: "#262884" }}>
                                <b>Shop by size</b>
                              </a>
                            </li>
                            <li>
                              <a href="single-product.html">
                                Small Single (2?6)
                              </a>
                            </li>
                            <li>
                              <a href="single-product-variable.html">
                                Single (3?0)
                              </a>
                            </li>
                            <li>
                              <a href="single-product-affiliate.html">
                                Small Double (4?0)
                              </a>
                            </li>
                            <li>
                              <a href="single-product-group.html">
                                Double (4?6)
                              </a>
                            </li>
                            <li>
                              <a href="single-product-tabstyle-2.html">
                                King (5?0)
                              </a>
                            </li>
                            <li>
                              <a href="single-product-tabstyle-3.html">
                                Super King (6?0)
                              </a>
                            </li>
                          </ul>
                        </li>
                      </ul>
                    </li>
                    <li className="dropdown position-static">
                      <a href="/Mattressess">
                        <b>Mattresses </b>
                      </a>

                      <ul className="mega-menu d-block">
                        <li className="d-flex">
                          <ul className="d-block">
                            <li>
                              <a className="p-0" href="shop-left-sidebar.html">
                                <Image
                                  className="img-responsive w-100"
                                  src="/assets/images/banner/Mattresses-nav.jpg"
                                  width={258}
                                  height={238}
                                  alt="BedsDivan"
                                />
                              </a>
                            </li>
                          </ul>
                          <ul className="d-block">
                            <li className="title">
                              <a href="#" style={{ color: "#262884" }}>
                                <b> Shop by Type </b>
                              </a>
                            </li>
                            <li>
                              <a href="shop-3-column.html">Plain Headboard</a>
                            </li>
                            <li>
                              <a href="shop-4-column.html">Panel Headboard</a>
                            </li>
                            <li>
                              <a href="shop-right-sidebar.html">
                                Cube Headboard
                              </a>
                            </li>
                            <li>
                              <a
                                href="shop-left-sidebar.html"
                                style={{ color: "#262884" }}
                              >
                                <b>View All</b>
                              </a>
                            </li>
                          </ul>
                          <ul className="d-block">
                            <li className="title">
                              <a href="#" style={{ color: "#262884" }}>
                                <b>Shop by size</b>
                              </a>
                            </li>
                            <li>
                              <a href="single-product.html">
                                Small Single (2?6)
                              </a>
                            </li>
                            <li>
                              <a href="single-product-variable.html">
                                Single (3?0)
                              </a>
                            </li>
                            <li>
                              <a href="single-product-affiliate.html">
                                Small Double (4?0)
                              </a>
                            </li>
                            <li>
                              <a href="single-product-group.html">
                                Double (4?6)
                              </a>
                            </li>
                            <li>
                              <a href="single-product-tabstyle-2.html">
                                King (5?0)
                              </a>
                            </li>
                            <li>
                              <a href="single-product-tabstyle-3.html">
                                Super King (6?0)
                              </a>
                            </li>
                          </ul>
                          <ul className="d-block">
                            <li className="title">
                              <a href="#" style={{ color: "#262884" }}>
                                <b>Shop by Comfort</b>
                              </a>
                            </li>
                            <li>
                              <a href="single-product.html">Very Firm</a>
                            </li>
                            <li>
                              <a href="single-product-variable.html">Firm</a>
                            </li>
                            <li>
                              <a href="single-product-affiliate.html">Medium</a>
                            </li>
                            <li>
                              <a href="single-product-group.html">Soft</a>
                            </li>
                          </ul>
                        </li>
                      </ul>
                    </li>

                    <li className="dropdown position-static">
                      <Link className="ForBold" href="/product/sofa">
                        Sofa
                      </Link>
                      {/* <i
                                            className="ion-ios-arrow-down"></i> */}
                      <ul className="mega-menu d-block">
                        <li className="d-flex">
                          <ul className="d-block">
                            <li>
                              <a className="p-0" href="shop-left-sidebar.html">
                                <Image
                                  width={258}
                                  height={238}
                                  className="img-responsive w-100"
                                  src="/assets/images/banner/Mattresses-nav.jpg"
                                  alt="BedsDivan"
                                />
                              </a>
                            </li>
                          </ul>
                          <ul className="d-block">
                            <li className="title">
                              <a href="#" style={{ color: "#262884" }}>
                                <b> Shop by Type </b>
                              </a>
                            </li>
                            <li>
                              <a href="shop-3-column.html">Chair beds</a>
                            </li>
                            <li>
                              <a href="shop-4-column.html">
                                2 seater sofa beds
                              </a>
                            </li>
                            <li>
                              <a href="shop-right-sidebar.html">
                                3 seater sofa beds
                              </a>
                            </li>
                            <li>
                              <a href="shop-right-sidebar.html">
                                4 seater sofa beds
                              </a>
                            </li>
                            <li>
                              <a href="shop-right-sidebar.html">
                                Corner sofa beds
                              </a>
                            </li>
                            <li>
                              <a href="shop-right-sidebar.html">
                                Storage sofa beds
                              </a>
                            </li>
                            <li>
                              <a href="shop-right-sidebar.html">
                                Fabric sofa beds
                              </a>
                            </li>
                            <li>
                              <a href="shop-right-sidebar.html">Chairs</a>
                            </li>
                            <li>
                              <a href="shop-right-sidebar.html">Footstools</a>
                            </li>
                          </ul>
                          <ul className="d-block">
                            <li className="title">
                              <a href="#" style={{ color: "#262884" }}>
                                <b>Fabric Sofa</b>
                              </a>
                            </li>
                            <li>
                              <a href="single-product.html">Champion Sofa</a>
                            </li>
                            <li>
                              <a href="single-product-variable.html">
                                Chicago Sofa
                              </a>
                            </li>
                          </ul>
                          <ul className="d-block">
                            <li className="title1">
                              <a href="#" style={{ color: "#262884" }}>
                                <b>Leather beds</b>
                              </a>
                            </li>
                            <li className="title1">
                              <a href="#" style={{ color: "#262884" }}>
                                <b>Nevada Beds</b>
                              </a>
                            </li>
                            <li className="title1">
                              <a href="#" style={{ color: "#262884" }}>
                                <b>Storage Bed</b>
                              </a>
                            </li>
                          </ul>
                        </li>
                      </ul>
                    </li>
                    <li className="dropdown position-static">
                      <Link href="/product/gardenfurniture">
                        Garden Furniture
                      </Link>
                      {/* <i
                                            className="ion-ios-arrow-down"></i> */}

                      <ul className="mega-menu d-block">
                        <li className="d-flex">
                          <ul className="d-block">
                            <li>
                              <a className="p-0" href="shop-left-sidebar.html">
                                <Image
                                  width={258}
                                  height={238}
                                  className="img-responsive w-100"
                                  src="/assets/images/banner/Mattresses-nav.jpg"
                                  alt="BedsDivan"
                                />
                              </a>
                            </li>
                          </ul>
                          <ul className="d-block">
                            <li className="title">
                              <a href="#" style={{ color: "#262884" }}>
                                <b> Shop by Type </b>
                              </a>
                            </li>
                            <li>
                              <a href="shop-3-column.html">Chair beds</a>
                            </li>
                            <li>
                              <a href="shop-4-column.html">
                                2 seater sofa beds
                              </a>
                            </li>
                            <li>
                              <a href="shop-right-sidebar.html">
                                3 seater sofa beds
                              </a>
                            </li>
                            <li>
                              <a href="shop-right-sidebar.html">
                                4 seater sofa beds
                              </a>
                            </li>
                            <li>
                              <a href="shop-right-sidebar.html">
                                Corner sofa beds
                              </a>
                            </li>
                            <li>
                              <a href="shop-right-sidebar.html">
                                Storage sofa beds
                              </a>
                            </li>
                            <li>
                              <a href="shop-right-sidebar.html">
                                Fabric sofa beds
                              </a>
                            </li>
                            <li>
                              <a href="shop-right-sidebar.html">Chairs</a>
                            </li>
                            <li>
                              <a href="shop-right-sidebar.html">Footstools</a>
                            </li>
                          </ul>
                          <ul className="d-block">
                            <li className="title">
                              <a href="#" style={{ color: "#262884" }}>
                                <b>Fabric Sofa</b>
                              </a>
                            </li>
                            <li>
                              <a href="single-product.html">Champion Sofa</a>
                            </li>
                            <li>
                              <a href="single-product-variable.html">
                                Chicago Sofa
                              </a>
                            </li>
                          </ul>
                          <ul className="d-block">
                            <li className="title1">
                              <a href="#" style={{ color: "#262884" }}>
                                <b>Leather beds</b>
                              </a>
                            </li>
                            <li className="title1">
                              <a href="#" style={{ color: "#262884" }}>
                                <b>Nevada Beds</b>
                              </a>
                            </li>
                            <li className="title1">
                              <a href="#" style={{ color: "#262884" }}>
                                <b>Storage Bed</b>
                              </a>
                            </li>
                          </ul>
                        </li>
                      </ul>
                    </li>

                    {/* <li className="dropdown "><a href="#"> <b> Garden Furniture </b></a>
                                    <ul className="sub-menu">
                                        <li className="dropdown position-static"><a href="blog-grid-left-sidebar.html">Garden Sofa Sets
                                             </a> 
                                        </li>
                                        <li className="dropdown position-static"><a href="blog-list-left-sidebar.html">Garden Dining Sets
                                            </a>
                                        </li>
                                    </ul>
                                </li> */}

                    <li className="dropdown position-static">
                      <Link href="/newproduct"> Living Room Furniture </Link>
                      {/* <i
                                            className="ion-ios-arrow-down"></i> */}
                      <ul className="mega-menu d-block">
                        <li className="d-flex">
                          <ul className="d-block">
                            <li>
                              <a className="p-0" href="shop-left-sidebar.html">
                                <Image
                                  width={258}
                                  height={238}
                                  className="img-responsive w-100"
                                  src="/assets/images/banner/Mattresses-nav.jpg"
                                  alt="BedsDivan"
                                />
                              </a>
                            </li>
                          </ul>
                          <ul className="d-block">
                            <li className="title1">
                              <a href="#" style={{ color: "#262884" }}>
                                <b>Chest Drawers</b>
                              </a>
                            </li>
                            <li className="title1">
                              <a href="#" style={{ color: "#262884" }}>
                                <b>Shelf</b>
                              </a>
                            </li>
                            <li className="title1">
                              <a href="#" style={{ color: "#262884" }}>
                                <b>Wardrobes</b>
                              </a>
                            </li>
                            <li className="title1">
                              <a href="#" style={{ color: "#262884" }}>
                                <b>Nevada Beds</b>
                              </a>
                            </li>
                            <li className="title1">
                              <a href="#" style={{ color: "#262884" }}>
                                <b>Storage Bed</b>
                              </a>
                            </li>
                          </ul>

                          <ul className="d-block">
                            <li className="title">
                              <a href="#" style={{ color: "#262884" }}>
                                <b>Chairs</b>
                              </a>
                            </li>
                            <li>
                              <a href="single-product.html">Arm Chairs</a>
                            </li>
                            <li>
                              <a href="single-product-variable.html">
                                Rocking Chairs
                              </a>
                            </li>
                            <li>
                              <a href="single-product-variable.html">
                                Lounge Chairs
                              </a>
                            </li>
                          </ul>
                        </li>
                      </ul>
                    </li>

                    <li className="dropdown position-static">
                      <Link href="/product/diningset"> Dining Set </Link>
                      {/* <i
                                            className="ion-ios-arrow-down"></i> */}
                      <ul className="mega-menu d-block">
                        <li className="d-flex">
                          <ul className="d-block">
                            <li>
                              <a className="p-0" href="shop-left-sidebar.html">
                                <Image
                                  width={258}
                                  height={238}
                                  className="img-responsive w-100"
                                  src="/assets/images/banner/Mattresses-nav.jpg"
                                  alt="BedsDivan"
                                />
                              </a>
                            </li>
                          </ul>
                          <ul className="d-block">
                            <li className="title">
                              <a href="#" style={{ color: "#262884" }}>
                                <b> Dining Table Set </b>
                              </a>
                            </li>
                            <li>
                              <a href="shop-3-column.html">
                                2 Seater Dining Sets
                              </a>
                            </li>
                            <li>
                              <a href="shop-4-column.html">
                                4 Seater Dining Sets
                              </a>
                            </li>
                            <li>
                              <a href="shop-right-sidebar.html">
                                6 Seater Dining Sets
                              </a>
                            </li>
                            <li>
                              <a href="shop-right-sidebar.html">
                                4 seater sofa beds
                              </a>
                            </li>
                            <li>
                              <a href="shop-right-sidebar.html">
                                8 Seater Dining Sets
                              </a>
                            </li>
                            <li>
                              <a
                                href="shop-right-sidebar.html"
                                style={{ color: "#262884" }}
                              >
                                <b>View All</b>
                              </a>
                            </li>
                          </ul>

                          <ul className="d-block">
                            <li className="title1">
                              <a href="#" style={{ color: "#262884" }}>
                                <b>Dining Chairs</b>
                              </a>
                            </li>
                            <li className="title1">
                              <a href="#" style={{ color: "#262884" }}>
                                <b>Dining Tables</b>
                              </a>
                            </li>
                            <li className="title1">
                              <a href="#" style={{ color: "#262884" }}>
                                <b>Sideboards</b>
                              </a>
                            </li>
                          </ul>
                        </li>
                      </ul>
                    </li>
                    <li>
                      <a href="contact.html" style={{ color: "red" }}>
                        <b>Sale</b>
                      </a>
                    </li>
                  </ul>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
